Feature/svc 1111
DeKapito/ZenPacks.training.OpenWeather pull request #1
Opened 2019-01-21 13:37 UTC by DeKapito

2019-01-22 09:48 UTC, azadorozhnyizenoss requested changes
👍 +1

2019-01-22 09:48 UTC, azadorozhnyizenoss commented on ZenPacks/training/OpenWeather/dsplugins.py
> +    def camel_case_to_snake(self, name):
cover this function by unitests. create module util.py and move it. Docstrings as well.

2019-01-22 09:48 UTC, azadorozhnyizenoss commented on ZenPacks/training/OpenWeather/dsplugins.py
> +                    'severity': SEVERITY_ERROR,
Clear this event

2019-01-22 09:48 UTC, azadorozhnyizenoss commented on ZenPacks/training/OpenWeather/dsplugins.py
> +                        '{}: failed to get conditions data for {}. Reason: {}'
no sense to duplicate the same string in summary

2019-01-22 09:48 UTC, azadorozhnyizenoss commented on ZenPacks/training/OpenWeather/dsplugins.py
> +            except (KeyError, TypeError):
IndexError

2019-01-22 09:48 UTC, azadorozhnyizenoss commented on ZenPacks/training/OpenWeather/dsplugins.py
> +                    'message':
summary=message. Specify summary
Please clear event
Generate different event for specific case

2019-01-22 09:48 UTC, azadorozhnyizenoss commented on ZenPacks/training/OpenWeather/modeler/plugins/OpenWeather/Locations.py
> +            message = '{}: {} not set. Get one from https://openweathermap.org/api'\
refactor this please :)

2019-01-22 09:48 UTC, azadorozhnyizenoss commented on ZenPacks/training/OpenWeather/modeler/plugins/OpenWeather/Locations.py
> +            except (KeyError, TypeError), e:
add ValueError for prepId, and IndexError

2019-01-22 09:48 UTC, azadorozhnyizenoss commented on ZenPacks/training/OpenWeather/zenpack.yaml
> +            eventClass: /Status
event with eventClass /Status is used for determine device status (UP or Down)

2019-01-24 09:34 UTC, ayavorskyi requested changes
good job 
keep on 👍

2019-01-24 09:34 UTC, ayavorskyi commented on ZenPacks/training/OpenWeather/dsplugins.py
> +                    'message': e,
make summary more concise and send message as `message`

2019-01-24 09:34 UTC, ayavorskyi commented on ZenPacks/training/OpenWeather/dsplugins.py
> +                    'summary': '',
add some message

2019-01-24 09:34 UTC, ayavorskyi commented on ZenPacks/training/OpenWeather/dsplugins.py
> +                    'eventKey': 'oweatherConditionsCollect_%s' % datasource.params['location_name'],
feel free to use format() :)

2019-01-24 09:34 UTC, ayavorskyi commented on ZenPacks/training/OpenWeather/dsplugins.py
>              except Exception, e:
replace , with as

2019-01-24 09:34 UTC, ayavorskyi commented on ZenPacks/training/OpenWeather/dsplugins.py
> +                data['events'].append({
think about creating a generic method for event creation

2019-01-24 09:34 UTC, ayavorskyi commented on ZenPacks/training/OpenWeather/dsplugins.py
>              data['maps'].append(
keep in mind in real world it's not the best idea to follow :) 
take a look at datasource property of components fileds
https://zenpack-sdk.zenoss.com/en/latest/yaml-classes-and-relationships.html#class-property-fields

2019-01-24 09:34 UTC, ayavorskyi commented on ZenPacks/training/OpenWeather/modeler/plugins/OpenWeather/Locations.py
> +        if not (apikey and apiver and locations):
take a look at any/all in python

2019-01-24 09:34 UTC, ayavorskyi commented on ZenPacks/training/OpenWeather/modeler/plugins/OpenWeather/Locations.py
> +                if len(response['RESULTS']) == 0:
if response['RESULTS']

2019-01-30 09:48 UTC, azadorozhnyizenoss approved these changes
well done!

2019-01-30 10:43 UTC, merged